name: CI-CD pipeline

on:
 push:
   branches:
     - "feature/**"
     - "main"
 pull_request:
   branches:
     - main
   types:
     - opened
     - synchronize
     - reopened

permissions:
  contents: read
  pull-requests: write
     
jobs:
 sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -iii -r . -f json -o bandit-report.json || true

   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     # if: always()
     with:
      name: bandit-findings
      path: bandit-report.json

 build_image:
  name: Build Image and Run Docker Scout Scan
  needs: sast_scan
  runs-on: ubuntu-22.04

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      run: docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USER }}/myapp:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1
      with:
        dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
        dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        image: ${{ secrets.DOCKERHUB_USER }}/myapp:latest
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
        # exit-code: true
        
    - name: Upload Docker Scout Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif
        
    - name: Save docker image
      run: |
         docker save \
         ${{ secrets.DOCKERHUB_USER }}/myapp:latest \
         -o myapp-image.tar

    - name: Upload Docker Image 
      uses: actions/upload-artifact@v4
      # if: always()
      with:
        name: docker-image
        path: myapp-image.tar        

 push_image:
   name: Push Image into Docker hub
   needs:
     - sast_scan
     - build_image

   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
   runs-on: ubuntu-22.04

   steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v4
       with:
         name: docker-image

     - name: Load docker image
       run: docker load -i myapp-image.tar

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

     - name: Push to Docker Hub
       run: docker push ${{ secrets.DOCKERHUB_USER }}/myapp:latest

   
    

   

   
